name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/setup-mise@v2

      - name: Set up Python ${{ matrix.python-version }}
        run: mise use python@${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm install -d

      - name: Lint with ruff
        run: pdm run ruff check .

      - name: Check formatting with ruff
        run: pdm run ruff format --check .

      - name: Type check with mypy
        run: pdm run mypy src

      - name: Test with pytest
        run: pdm run pytest
