name: CI
on: [push, pull_request]

jobs:
  qa:
    name: "QA (${{ matrix.python-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install --dev

      - name: Check for vulnerable dependencies
        run: pdm run safety

      - name: Run QA Suite (Format, Lint, Types, Tests)
        run: pdm run qa