name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Python version from pyproject.toml
        id: python-version
        run: |
          VERSION=$(grep -E "^requires-python" pyproject.toml | sed -E 's/.*">=([0-9]+\.[0-9]+).*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install dependencies
        run: pdm install --dev

      - name: Configure Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run Semantic Release
        run: pdm run semantic-release publish
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}